routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login/{provider}', 'SocialController@redirect');
Route::get('login/{provider}/callback','SocialController@Callback');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::post('logout-and-delete', 'Auth\LoginController@logoutAndDelete')->name('logout-and-delete');

    Route::get('/', 'IndexController@index')->name('index');

    Route::get('profile', 'UserController@profile')->name('profile');
    Route::put('user/{user}', 'UserController@update')->name('user.update');
    Route::post('avatar/{user}', 'UserController@saveAvatar')->name('user.avatar');

    Route::get('domains', 'DomainController@index')->name('domains');
    Route::get('hostings', 'HostingController@index')->name('hostings');

    Route::get('buttons', 'IndexController@index')->name('buttons');
    Route::get('cards', 'IndexController@index')->name('cards');
    Route::get('utilities-color', 'IndexController@index')->name('utilities-color');
    Route::get('utilities-border', 'IndexController@index')->name('utilities-border');
    Route::get('utilities-animation', 'IndexController@index')->name('utilities-animation');
    Route::get('utilities-other', 'IndexController@index')->name('utilities-other');
    Route::get('charts', 'IndexController@index')->name('charts');
    Route::get('tables', 'IndexController@index')->name('tables');
});

app/User.php
<?php

namespace App;

use App\Models\Address;
use App\Models\UserDomain;
use App\Models\UserHosting;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use SoftDeletes, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'avatar',
        'provider',
        'provider_id',
        'email_verified_at',
        'discount',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'deleted_at'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $dates = ['deleted_at'];

    /**
     * @return mixed|string
     */
    public function getAvatarUrlAttribute()
    {
        return $this->avatar ?: asset('img/default-avatar.jpg');
    }

    /**
     * @return HasMany
     */
    public function userDomains()
    {
        return $this->hasMany(UserDomain::class);
    }

    /**
     * @return HasMany
     */
    public function userHostings()
    {
        return $this->hasMany(UserHosting::class);
    }

    /**
     * @return HasMany
     */
    public function addresses()
    {
        return $this->hasMany(Address::class);
    }

    /**
     * @return Model|HasMany|object|null
     */
    public function getMainAddressAttribute()
    {
        return $this->addresses()->where('is_main', 1)->first();
    }
}

resources/views/index.blade.php
@extends('layouts.page')

@section('page-content')
    <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>
@endsection

resources/views/profile.blade.php
@extends('layouts.page')

@section('page-content')
    <h1 class="h3 mb-4 text-gray-800">Profile</h1>

    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif

    <div class="row">
        <div class="col-xl-2 col-md-4 col-md-4 col-sm-12">
            <div class="main-avatar-div">
                <img
                    class="img-main-avatar rounded-circle"
                    id="img-main-avatar"
                    alt="Click to load new avatar"
                    src="{{ $user->avatar_url }}"
                />
            </div>
            <form id="avatar-form" method="POST" action="{{ route('user.avatar', $user->id) }}" enctype="multipart/form-data">
                <div>
                    <input type="file" name="avatar" accept="image/*" style="display: none" id="selectFileDialog">
                </div>
                <div>
                    <button id="uploadnow" style="display: none" class="btn btn-primary small">
                        Upload now!
                    </button>
                </div>
                <div class="ajax-respond"></div>

                @error('avatar')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </form>

        </div>

        <div class="col-md-6 col-sm-12">
            <form class="user" method="POST" action="{{ route('user.update', $user->id) }}">
                @csrf

                <input type="hidden" name="_method" value="PUT">

                <div class="form-group">
                    <input
                        id="name"
                        type="text"
                        class="form-control form-control-user @error('name') is-invalid @enderror"
                        placeholder="Name"
                        name="name"
                        value="{{ old('name', $user->name) }}"
                        autocomplete="name"
                        autofocus
                    >

                    @error('name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>

                <div class="form-group">
                    <input
                        id="email"
                        type="email"
                        class="form-control form-control-user @error('email') is-invalid @enderror"
                        placeholder="Email Address"
                        name="email"
                        value="{{ old('email', $user->email) }}"
                        autocomplete="email"
                    >

                    @error('email')
                    <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                    @enderror
                </div>

                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <input
                            id="password"
                            type="password"
                            class="form-control form-control-user @error('password') is-invalid @enderror"
                            placeholder="New Password"
                            name="password"
                            autocomplete="new-password"
                        >

                        @error('password')
                        <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                        @enderror
                    </div>
                    <div class="col-sm-6">
                        <input
                            id="password-confirm"
                            type="password"
                            class="form-control form-control-user"
                            name="password_confirmation"
                            placeholder="Repeat New Password"
                            autocomplete="new-password"
                        >
                    </div>
                </div>

                <hr>

                <div class="form-group">
                    <input
                        id="country"
                        type="text"
                        class="form-control form-control-user @error('address.country') is-invalid @enderror"
                        placeholder="Country"
                        name="address[country]"
                        value="{{ old('address.country', $user->mainAddress ? $user->mainAddress->country : null) }}"
                        autocomplete="country"
                        autofocus
                    >

                    @error('address.country')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="form-group">
                    <input
                        id="city"
                        type="text"
                        class="form-control form-control-user @error('address.city') is-invalid @enderror"
                        placeholder="City"
                        name="address[city]"
                        value="{{ old('address.city', $user->mainAddress ? $user->mainAddress->city : null) }}"
                        autocomplete="city"
                        autofocus
                    >

                    @error('address.city')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="form-group">
                    <input
                        id="street"
                        type="text"
                        class="form-control form-control-user @error('address.street') is-invalid @enderror"
                        placeholder="Street"
                        name="address[street]"
                        value="{{ old('address.street', $user->mainAddress ? $user->mainAddress->street : null) }}"
                        autocomplete="street"
                        autofocus
                    >

                    @error('address.street')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="form-group">
                    <input
                        id="zip_code"
                        type="text"
                        class="form-control form-control-user @error('address.zip_code') is-invalid @enderror"
                        placeholder="Zip code"
                        name="address[zip_code]"
                        value="{{ old('address.zip_code', $user->mainAddress ? $user->mainAddress->zip_code : null) }}"
                        autocomplete="zip_code"
                        autofocus
                    >

                    @error('address.zip_code')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <button type="submit" class="btn btn-primary btn-user btn-block">
                    Save
                </button>
            </form>
        </div>
    </div>

@endsection