routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login/{provider}', 'SocialController@redirect');
Route::get('login/{provider}/callback','SocialController@Callback');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::post('logout-and-delete', 'Auth\LoginController@logoutAndDelete')->name('logout-and-delete');

    Route::get('/', 'IndexController@index')->name('index');

    Route::get('profile', 'UserController@profile')->name('profile');
    Route::put('user/{user}', 'UserController@update')->name('user.update');
    Route::post('avatar/{user}', 'UserController@saveAvatar')->name('user.avatar');

    Route::get('domains', 'DomainController@index')->name('domains');
    Route::get('hostings', 'HostingController@index')->name('hostings');

    Route::get('buttons', 'IndexController@index')->name('buttons');
    Route::get('cards', 'IndexController@index')->name('cards');
    Route::get('utilities-color', 'IndexController@index')->name('utilities-color');
    Route::get('utilities-border', 'IndexController@index')->name('utilities-border');
    Route::get('utilities-animation', 'IndexController@index')->name('utilities-animation');
    Route::get('utilities-other', 'IndexController@index')->name('utilities-other');
    Route::get('charts', 'IndexController@index')->name('charts');
    Route::get('tables', 'IndexController@index')->name('tables');
});

app/Models/Hosting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\PricingPlan;
use App\Models\HostingFeature;
use App\Models\Page;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Hosting extends Model
{
    protected $fillable = [
        'name',
        'title',
        'menu_img_path',
        'description',
        'is_active',
        'icon',
        'section_title',
        'section_description',
        'section_img'
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    /**
     * @return HasMany
     */
    public function pricingPlans()
    {
        return $this->hasMany(HostingPricingPlan::class, 'hosting_id');
    }

    /**
     * @return BelongsToMany
     */
    public function features()
    {
        return $this->belongsToMany(HostingFeature::class, 'hosting_hosting_feature', 'hosting_id', 'feature_id');
    }
}

app/Models/UserHosting.php
<?php

namespace App\Models;

use App\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class UserHosting extends Model
{
    protected $fillable = [
        'user_id',
        'plan_id',
        'type_id',
        'start_date',
        'total_cost',
        'is_active',
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    protected $dates = [
        'start_date'
    ];

    /**
     * @return BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return BelongsTo
     */
    public function pricingPlan()
    {
        return $this->belongsTo(HostingPricingPlan::class, 'plan_id');
    }

    /**
     * @return BelongsTo
     */
    public function type()
    {
        return $this->belongsTo(PricingPlanType::class, 'type_id');
    }

    public function setTotalCostAttribute()
    {
        $planDiscount = $this->pricingPlan->discount->{$this->type->name} ?? 0;
        $totalDiscount = $planDiscount + $this->user->discount;
        $fullPrice = $this->pricingPlan->monthly_price * $this->type->duration;
        $totalCost =  $fullPrice - $fullPrice * $totalDiscount * 0.01;

        $this->attributes['total_cost'] = $totalCost;
    }

    /**
     * @return Carbon
     */
    public function getExpiryDateAttribute()
    {
        return Carbon::parse($this->start_date)->addMonth($this->type->duration);
    }
}

app/Http/Controllers/HostingController.php
<?php

namespace App\Http\Controllers;

use App\Models\UserDomain;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HostingController extends Controller
{
    public function index()
    {
        return view('hosting.index')->with([
            'hostings' => Auth::user()->userHostings
        ]);
    }
}

resources/views/hosting/index.blade.php
@extends('layouts.page')

@section('page-content')
    <h1 class="h3 mb-4 text-gray-800">Domain List</h1>

    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif

    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Plan</th>
                            <th>Status</th>
                            <th>Hosting features</th>
                            <th>Type</th>
                            <th>Start date</th>
                            <th>Date of Expiry</th>
                            <th>Price</th>

                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($hostings as $hosting)
                            <tr>
                                <td>{{ $hosting->pricingPlan->name }}</td>
                                <td>{{ $hosting->is_active }}</td>
                                <td>
                                    <ul>
                                        <li class="list1">{{ $hosting->pricingPlan->disk_space }}GB SSD Space</li>
                                        <li class="list2">{{ $hosting->pricingPlan->memory }}MB Memory</li>
                                        <li class="list3">{{ $hosting->pricingPlan->vcpu_core_count }} Core vCPU</li>
                                        <li class="list4">{{ $hosting->pricingPlan->bandwidth }} TB/mo Bandwidth</li>
                                        <li class="list5">{{ $hosting->pricingPlan->mysql }}</li>
                                        <li class="list6">{{ $hosting->pricingPlan->emails_count }} E-mails</li>
                                        <li class="list7">{{ $hosting->pricingPlan->ftp_accounts_count }} FTP Accounts</li>
                                        <li class="list8">{{ $hosting->pricingPlan->support }}</li>
                                    </ul>
                                </td>
                                <td>{{ $hosting->type->title }}</td>
                                <td>{{ $hosting->start_date }}</td>
                                <td>{{ $hosting->expiry_date }}</td>
                                <td>{{ $hosting->total_cost }}</td>
                                <td>
                                    <a href="#" class="btn btn-warning btn-circle btn-sm">
                                        <i class="fas fa-cog"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection